function joystickDevInds = connectToJoysticks(joystickName)
% Here be code to grab the joystick device number, which is needed for
% querying it with PsychToolbox; do it before anything appears on the
% screen to make timing better

allGamepadLike = Gamepad('GetNumGamepads');
gamepadNames = Gamepad('GetGamepadNamesFromIndices', 1:allGamepadLike);
joystickDevInds = find(~cellfun('isempty', strfind(gamepadNames, joystickName)));
if length(joystickDevInds) > 1
    numAx = [];
    for i = 1:length(joystickDevInds)
        numAx = [numAx Gamepad('GetNumAxes', joystickDevInds(i))];
    end
    joystickDevInds = joystickDevInds(numAx ~= 0);
end

if isempty(joystickDevInds)
    error(['\n\nNo connected joystick found! Perhaps the name has changed? If you think \n'...
        'that might be the case, check the names of the available GamePads using \n\n'...
        '    [ind, name] = GetGamepadIndices \n\n'...
        'and check the output names against the joystickName value in the XML \n'...
        'file (currently %s). You might have to see what name disappears after \n'...
        'unplugging the joystick if you''re not sure which name refers to the \n'...
        'joystick. \n\n'...
        '(For the code-hunters among us, realize that the inds found in the \n'...
        'output variable ind do not actually match the deviceInd expected in other \n'...
        'GamePad functions, and the way it''s done in the code is the way it has to \n'...
        'be done. For the not code-hunters, don''t worry about it.) \n\n'], joystickName)
end